/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bank;

import bank.domain.entities.Account;
import bank.domain.entities.Bank;
import bank.domain.entities.CheckingAccount;
import bank.domain.entities.Client;
import bank.domain.entities.SavingsAccount;
import bank.domain.exceptions.InsufficientFundsException;
import bank.domain.exceptions.InvalidValueException;

public class App {
    public static void main(String[] args) throws InvalidValueException, InsufficientFundsException {
        Bank digitalBank = new Bank("Digital Bank");

        Client client1 = new Client("John Doe");
        Client client2 = new Client("Jane Doe");

        CheckingAccount checkingAccount = new CheckingAccount(client1);
        SavingsAccount savingsAccount = new SavingsAccount(client2);

        digitalBank.getAccounts().add(checkingAccount);
        digitalBank.getAccounts().add(savingsAccount);

        checkingAccount.deposit(50.62);
        savingsAccount.deposit(154.31);

        checkingAccount.withdraw(25);
        savingsAccount.withdraw(10.88);

        checkingAccount.setOverdraft(1000.50);
        checkingAccount.withdraw(500);

        checkingAccount.printBalance();
        savingsAccount.printBalance();

        digitalBank.transfer(checkingAccount, savingsAccount, 15.25);

        checkingAccount.printBalance();
        savingsAccount.printBalance();

        System.out.println("Bank Accounts:");
        for (Account acc : digitalBank.getAccounts()) {
            System.out.println("- " + acc);
        }
    }
}
